version: "3.8"
services:
  mysql:
    container_name: review_sql
    image: mysql:latest
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : crud_mysql
      MYSQL_PASSWORD : password
    ports:
      - "3301:3306"